print("Las máquinas me sorprenden con mucha frecuencia")
print("")
print("HOLA MUNDO")
print("23")
print(23)
print("Una computadora puede ser llamada", '"inteligente"',"si logra engañar a una persona haciéndole creer que es un humano")
print("Susana Gabriela","Bockelmann Miller","36")
print("Susana Gabriela","Bockelmann Miller","36",sep="_")
print("calle","numero","codigopostal",sep="\t")
print("\n","calle","\n","numero","\n","codigopostal")
print("\n","feliz","\n","\t","Primavera","\n","\n","\t","\t","\t","2024")
print("Solo podemos ver poco del futuro", end=" ")
print("pero lo suficiente para darnos cuenta de que hay mucho que hacer")
print("      *")
print("    *   *")
print("   *     *")
print("  *       *")
print(" ***     ***")
print("    *   *")
print("    *   *")
print("    *****")
print()