print("      *")
print("    *   *")
print("   *     *")
print("  *       *")
print(" ***     ***")
print("    *   *")
print("    *   *")
print("    *****")

#punto 19
print("      *","\n","   *   *","\n","  *     *","\n"," *       *","\n","***     ***","\n","   *   *","\n","   *   *","\n","   *****")

print("      *"*2)
print("    *   *"*2,"\t")
print("   *     *"*2,"\t")
print("  *       *"*2)
print(" ***     ***"*2)
print("    *   *"*2)
print("    *   *"*2)
print("    *****"*2)